#pragma once

#define WINDER_STEP_PIN 54
#define WINDER_DIR_PIN 55
#define WINDER_EN_PIN 38
#define WINDER_ENDSTOP_MIN 14
#define WINDER_ENDSTOP_MAX 3
#define WINDER_SPOOL_ROTATION_SEN 2

#define WINDER_FILAMENT_WIDTH_STEPS 100

#define WINDER_SPOOLER_MOTOR 10